// This file is generated by AnimatorUtils.

public struct AnimatorHashes
{
    // States
    public const int AttackState = 1130333774;
    public const int LocomotionState = -1269438207;

    // Parameters
    public const int SpeedFloat = -823668238;
}
