// This file is generated by AnimatorUtils.

public struct SkeletonHashes
{
// States
    public const int BaseLayer_AttackState = 61898150;
    public const int BaseLayer_LocomotionState = -1321881004;
    public const int BaseLayer_DeathState = -1824900286;

// Parameters
    public const int SpeedFloat = -823668238;
}
